This nearly broke me, the complications involved here where somewhat overwhelming for the beginning of a course like this and instilled a sort of dread regarding git, git hub, git lab, visual studio code and the interactions of all of them. I think my first hurdle was how to go about the definitions problem of the data types, are these two python problems lists or dictionaries? Neither really seems to fit the bill, a list typically can be defined in the line in which was defined, and dictionaries require a level of complexity of defining the values and then giving an example all the while expressing what the value is a tuple, a string?

Then come the difficulties in calling the csv files, relative paths where explained in our course, but up to this point in time we have been using csv files that were automatically included in the unsolved section of the activity, so I may understand how to call a csv file that is a folder up or nextdoor to the whatever python activity we've been working on, I don't have the technical competency to write something that is callable not relative to myself and my local directory, but retrievable in a remote repository that I will be posting this challenge to. So how one goes about writing that in VSCode is an unnecessary complication at this point, I can either write it the way that I know how using my C:\users\DataClass amd just not have it work when I post it here, or have to figure out how to call a remote repository using a relative path. It was unnecessarily complicated and discouraging, not only because after one figures out how to do that, the PyPoll csv is to large to push conventionally.

So one finds Pathlib and how to get the current working directory, but at that point im sort of discouraged, especially with the complications of git and git hub. I wound up cloning a remote repository onto my local machine, and seemingly all of the tutorials published by this course, git's offical published documentation available on their website use outdate phrases. Like okay, I get that until a year ago every 'main' branch was refered to as 'master' but that wasn't told to us, so in looking through tutorials on how to push to a remote repository I overwrote my main branch as 'Master'dutifully following Git's published documentation on the subject, and messed things up pretty quickly for myself with 3 remote branches and two local python-challenges required to fix all of that, and then naturally, I publish the wrong working directory and link that to the submission link on the website.

I just think that this was overly frustrating for so early in the course and yeah okay I got some stuff to print and I was able to do totals but beyond the functions of for loops and max and min there wasn't much to be gleemed from this exercise.

11/10
Okay so I did as the central grader suggested in that I called all of the variables before even starting the exercise, ever single one. I get it, I understand that I was getting the divide by zero error
because the for loop wasn't actually looping anywhere because the variables had been called inside the loop and so didn't exist outside of that loop, and as there wasn't at a catchall list it wasn't going anywhere.
Henry my TA helped on this explaining what the grader meant, and he showed me why I was getting the output put that I was getting and then left me to figure it out what the problem was. It was as simple as that really,
I just declared everything rather than as I went and there were not conflicts. However, this exercise seems to be my great white whale, I am exponentially more confident in my skills and knowledge base since this exercise was first
attempted, or at least so I thought. Of course, of course I would somehow create another working branch in the python file, but as I seem to recall that other branch Matt was only for project 3 so we could use git as intended. Didn't work out that way
what happened was I made a branch off from main since I was hosting the project file, and then my partners just made directories to keep their portions seperate. But as I had unleashed the second branch genie again, read up dear grader for a better understanding of my well earned fear of branches.
the branch, like the infectioius disease that it is somehow managed to make it into my python challenge git hub remote, and so then a merge conflict ensued, I handled it better this time, but accidentally deleted the main->pybank and pypoll that I wanted to keep, luckily I copied them and put them somewhere else
cause this merge conflict sort of blindsided me, anyway the PyBank works as intended, I checked again. 
